### ISSUE TITLE
请问 m3u8和 key 的 base url 不一致的情况下，该怎么使用

### ISSUE THREAD

**Issue by yunchenran** [cxjava/m3u8-downloader#27]
抓包发现 m3u8和 key 的 base url 不一致，我尝试手动下载 key 文件，但是发现没有支持直接使用 key 文件的命令参数，现在无法解密

**Comment by cxjava** [comment]
开始是默认key url和 m3u8是同一个domain，这个可能需要你自己修改代码了

大概在 https://github.com/cxjava/m3u8-downloader/blob/main/downloader/m3u8.go#L222 这个地方。

**Comment by cxjava** [comment]
看起来变得比较好玩的了，这种情况只能自己手动解密了，还有那种这个key也不是真正解密的key，需要你用key做变换的
